version: "3.9"
services:
    web:
        build:
            context: .
            Dockerfile: ./Dockerfile.frontend
    ports:
        - "80:80"
    web-server:
        image: node:lts
    mongoDB:
        image: mongo:6
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
